#!/bin/bash
# Scaffold a tailscale-served launchd dashboard service on this Mac.
# Writes ~/.local/bin/run-<name>.sh and stages a LaunchDaemon plist at
# ~/.local/share/<name>/com.hans.<name>.plist, then prints the sudo install/load
# handoff (which must be run by the user — the agent shell has no TTY for sudo,
# and the system domain needs root).
#
# Why a LaunchDaemon (system domain), not a LaunchAgent (gui/$UID): the agent's
# shell is a background/SSH session that can't reach gui/$UID, and a daemon
# survives reboots without a login session. It runs as root, so UserName/GroupName
# drop it back to the user.
#
# Idempotent and non-destructive: refuses to reuse a tailnet --https port that
# `tailscale serve status` already maps to a DIFFERENT local port.
set -euo pipefail

TS=/Applications/Tailscale.app/Contents/MacOS/Tailscale
PYTHON_DEFAULT=/Users/hans/homebrew/bin/python3.14
HOME_DIR=/Users/hans

usage() {
    cat <<'EOF'
Usage: scaffold.sh --name NAME --port LOCAL_PORT --https TAILNET_PORT --app PATH [options]

Required:
  --name NAME        service short name (label becomes com.hans.NAME)
  --port LOCAL_PORT  loopback port the app listens on (bound to 127.0.0.1)
  --https PORT       tailnet HTTPS port to expose via `tailscale serve`
  --app PATH         absolute path to the app/script to run

Options:
  --python PATH      python interpreter (default: /Users/hans/homebrew/bin/python3.14)
  --user NAME        UserName the daemon drops to (default: hans)
  --group NAME       GroupName the daemon drops to (default: staff)
  --args "STRING"    extra args after the app (default: "--host 127.0.0.1 --port LOCAL_PORT")
  --no-caffeinate    don't wrap in `caffeinate` (for stateless view-only dashboards)
  --no-python        --app is itself executable; run it directly, not via python
  -h, --help         this help
EOF
}

NAME='' PORT='' HTTPS='' APP='' PYTHON="$PYTHON_DEFAULT"
USERNAME='hans' GROUPNAME='staff'
ARGS='' CAFFEINATE=1 USE_PYTHON=1 ARGS_SET=0

while [ $# -gt 0 ]; do
    case "$1" in
        --name) NAME="$2"; shift 2;;
        --port) PORT="$2"; shift 2;;
        --https) HTTPS="$2"; shift 2;;
        --app) APP="$2"; shift 2;;
        --python) PYTHON="$2"; shift 2;;
        --user) USERNAME="$2"; shift 2;;
        --group) GROUPNAME="$2"; shift 2;;
        --args) ARGS="$2"; ARGS_SET=1; shift 2;;
        --no-caffeinate) CAFFEINATE=0; shift;;
        --no-python) USE_PYTHON=0; shift;;
        -h|--help) usage; exit 0;;
        *) echo "unknown arg: $1" >&2; usage; exit 2;;
    esac
done

for v in NAME PORT HTTPS APP; do
    if [ -z "${!v}" ]; then echo "missing required --${v,,}" >&2; usage; exit 2; fi
done
[ "$ARGS_SET" -eq 1 ] || ARGS="--host 127.0.0.1 --port ${PORT}"

# Guard: don't clobber an existing tailnet :HTTPS mapping that points elsewhere.
if [ -x "$TS" ]; then
    existing=$("$TS" serve status 2>/dev/null | grep -E ":${HTTPS} " -A1 | grep -oE '127\.0\.0\.1:[0-9]+' || true)
    if [ -n "$existing" ] && [ "$existing" != "127.0.0.1:${PORT}" ]; then
        echo "REFUSING: tailnet :${HTTPS} already proxies to ${existing} (not 127.0.0.1:${PORT})." >&2
        echo "Pick a different --https port. Current mappings:" >&2
        "$TS" serve status >&2
        exit 1
    fi
fi

RUN="${HOME_DIR}/.local/bin/run-${NAME}.sh"
INSTALL="${HOME_DIR}/.local/bin/install-${NAME}.sh"
STAGE_DIR="${HOME_DIR}/.local/share/${NAME}"
PLIST="${STAGE_DIR}/com.hans.${NAME}.plist"
DEST="/Library/LaunchDaemons/com.hans.${NAME}.plist"
LABEL="com.hans.${NAME}"
mkdir -p "$STAGE_DIR"

# --- run script ---
if [ "$USE_PYTHON" -eq 1 ]; then EXECLINE="\"\$PYTHON\" \"\$APP\" ${ARGS}"; else EXECLINE="\"\$APP\" ${ARGS}"; fi
if [ "$CAFFEINATE" -eq 1 ]; then PREFIX="/usr/bin/caffeinate -i -s "; else PREFIX=""; fi

cat > "$RUN" <<EOF
#!/bin/bash
# Entry point for the com.hans.${NAME} LaunchDaemon. Generated by scaffold.sh.
set -euo pipefail
TS=${TS}
PYTHON=${PYTHON}
APP=${APP}
PORT=${PORT}

# Re-assert the tailscale serve mapping: additive + idempotent.
if [ -x "\$TS" ]; then
    if ! "\$TS" serve status 2>/dev/null | grep -q "127.0.0.1:\${PORT}"; then
        "\$TS" serve --bg --https=${HTTPS} / "http://127.0.0.1:\${PORT}" || true
    fi
fi

exec ${PREFIX}${EXECLINE}
EOF
chmod +x "$RUN"

# --- LaunchDaemon plist (staged; user copies to /Library/LaunchDaemons via sudo) ---
cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.hans.${NAME}</string>
    <key>ProgramArguments</key>
    <array>
        <string>${RUN}</string>
    </array>
    <!-- Daemon runs as root by default; drop to the user so HOME-relative state resolves. -->
    <key>UserName</key>
    <string>${USERNAME}</string>
    <key>GroupName</key>
    <string>${GROUPNAME}</string>
    <key>WorkingDirectory</key>
    <string>${HOME_DIR}/.local/bin</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>HOME</key>
        <string>${HOME_DIR}</string>
        <key>PATH</key>
        <string>${HOME_DIR}/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
    </dict>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>ThrottleInterval</key>
    <integer>10</integer>
    <key>StandardOutPath</key>
    <string>${HOME_DIR}/Library/Logs/${NAME}.log</string>
    <key>StandardErrorPath</key>
    <string>${HOME_DIR}/Library/Logs/${NAME}.err.log</string>
</dict>
</plist>
EOF

# --- single installer the user runs themselves (calls sudo internally) ---
cat > "$INSTALL" <<EOF
#!/bin/bash
# Install + (re)load ${LABEL} as a system LaunchDaemon. Generated by scaffold.sh.
# Run yourself in a normal Terminal — it calls sudo and will prompt for your
# password. Idempotent: safe to re-run after editing the plist.
set -euo pipefail
LABEL=${LABEL}
SRC=${PLIST}
DEST=${DEST}
PORT=${PORT}

[ -f "\$SRC" ] || { echo "missing staged plist: \$SRC" >&2; exit 1; }
plutil -lint "\$SRC" >/dev/null

echo "==> stopping any manually-started instance (frees :\${PORT})"
pkill -f run-${NAME}.sh 2>/dev/null || true
pkill -f '${APP##*/}'   2>/dev/null || true
sleep 1

echo "==> installing \$DEST (root:wheel, 644)"
sudo cp "\$SRC" "\$DEST"
sudo chown root:wheel "\$DEST"
sudo chmod 644 "\$DEST"

echo "==> (re)loading in the system domain"
sudo launchctl bootout system/\${LABEL} 2>/dev/null || true
sudo launchctl bootstrap system/ "\$DEST"
sudo launchctl enable system/\${LABEL} 2>/dev/null || true

echo "==> waiting for the daemon to come up"
code=000
for i in \$(seq 1 10); do
    code=\$(curl -s -o /dev/null -w '%{http_code}' "http://127.0.0.1:\${PORT}/" --max-time 2 || true)
    [ "\$code" = "200" ] && break
    sleep 1
done

echo
echo "==> status"
sudo launchctl print system/\${LABEL} | grep -E 'state =|pid =' || true
echo "    local http://127.0.0.1:\${PORT}/ -> HTTP \${code}"
[ "\$code" = "200" ] && echo "==> OK" || { echo "==> NOT healthy — check ~/Library/Logs/${NAME}.err.log" >&2; exit 1; }
EOF
chmod +x "$INSTALL"

plutil -lint "$PLIST" >/dev/null
echo "wrote   $RUN"
echo "staged  $PLIST"
echo "wrote   $INSTALL"
echo
echo "To install + load it, run this yourself in a normal Terminal (it uses sudo):"
echo "    $INSTALL"
